#!/bin/bash

# Usage function to help user  
user_usage() {
  echo "Usage: $0 [OPTIONS] <DIRECTORY>"
  echo "USAGE OPTIONS: These are the things you can do! "
  echo "  -e             Condition to delete all empty files (e for empty)"
  echo "  -o <DAYS>      Condition to delete all old files"
  echo "  -s <SIZE>      Condition to delete all files larger than a certain size"
  echo "  -t <TYPE>      Condition to delete all files of a specific type"
  echo "  -a             Condition to delete ALL files in the directory"
  echo "  -h             Condition to display the help message!"
}

# Different options , variables initialized 
EMPTY_DEL=0
OLD_DEL=0
SIZE_DEL=0
TYPE_DEL=0
ALL_DEL=0
AGE_THRESHOLD=0
SIZE_THRESHOLD=""
FILE_TYPE=""

while getopts "eo:s:t:a h" option; do 
  case "$option" in
    e) EMPTY_DEL=1 ;;  # Flag to delete empty files
    o) OLD_DEL=1; AGE_THRESHOLD=$OPTARG ;;  # Age amount, provided by user 
    s) SIZE_DEL=1; SIZE_THRESHOLD=$OPTARG ;;  # Size amount, provided by user
    t) TYPE_DEL=1; FILE_TYPE=$OPTARG ;;  # Delete certain types 
    a) ALL_DEL=1 ;;   # Used to delete all files 
    h) usage; exit 0 ;;  # Success, exit with code 0
    *) usage; exit 1 ;;  # Error, exit with code 1
  esac
done

shift $((OPTIND - 1))  #go through options

#Make sure a directory is given or specific argument for file type, age, size needed
if [ -z "$1" ]; then
  echo "Uh-oh no directory provided or a specific argument is needed!"
  usage
  exit 1
fi

DIRECTORY=$1

# Directory provided, make sure it exists
if [ ! -d "$DIRECTORY" ]; then
  echo "Uh-oh '$DIRECTORY' does not exist!"
  exit 1
fi

# Go to directory 
cd "$DIRECTORY" || exit

#This option deletes all the empty files in the directory if selected
if [ "$EMPTY_DEL" -eq 1 ]; then 
  echo "All files that are empty, are being deleted! "
  find . -type f -empty -exec echo {} \; -exec rm -f {} \;
fi

#This option deletes files of certain age (older than a certain number of days)
if [ "$OLD_DEL" -eq 1 ]; then
  echo "All files older than $AGE_THRESHOLD days are being deleted!"
  find . -type f -mtime +$AGE_THRESHOLD -exec echo {} \; -exec rm -f {} \;
fi

#This option deletes files of certain sizes in the directory
if [ "$SIZE_DEL" -eq 1 ]; then
  echo "All $SIZE_THRESHOLD sized files are being deleted!"
  find . -type f -size +$SIZE_THRESHOLD -exec echo {} \; -exec rm -f {} \;
fi

#This option deletes specific types of files in the directory
if [ "$TYPE_DEL" -eq 1 ]; then
  echo "All $FILE_TYPE files are being deleted!"
  find . -type f -name "*.$FILE_TYPE" -exec echo {} \; -exec rm -f {} \;
fi

# This option deletes all the files in the directory if needed 
if [ "$ALL_DEL" -eq 1 ]; then
  echo "ALL files are being deleted!"
  find . -type f -exec echo {} \; -exec rm -f {} \;
fi

echo "Cleaned Up!"  #end of cleanup indicated via echo
